name: CI

on:
  push:
    branches: ['**/*']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Full Install
        run: npm run full-install

      - name: Prettier Check
        run: npx prettier ./ --ignore-unknown --check

      - name: Linting
        run: npm run lint

      - name: Server Tests
        working-directory: server
        run: npx jest --ci

      - name: Client Unit Tests
        working-directory: client
        run: npm run test-unit

      - name: Build Server
        working-directory: server
        run: npm run build

      - name: Build Client
        working-directory: client
        run: npm run build

      - name: Cypress Component Tests
        working-directory: client
        run: npx cypress run-ct

      - name: Cypress End to End
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        run: npm run cypress:ci

      - name: Save screenshots
        if: always() # run this step even if previous step failed
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Save videos
        if: always() # run this step even if previous step failed
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: client/cypress/videos
