name: CI

on:
  push:
    branches: ['**/*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm run full-install
      - name: Linting
        run: npm run lint
      - name: Client Tests
        run: npm run client:unit
      - name: Server Tests
        run: npm run server:test
      - name: Build Client
        run: npm run client:build
      - name: Build Server
        run: npm run server:build
