name: CI

on:
  push:
    branches: ['**/*']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Full Install
        run: npm run full-install

      - name: Linting
        run: npm run lint

      - name: Server Tests
        run: npm run server:test

      - name: Client Unit Tests
        run: npm run client:unit

      - name: Build Server
        working-directory: server
        run: npm run build

      - name: Build Client
        working-directory: client
        run: npm run build

      - name: Cypress Component Tests
        working-directory: client
        run: npx cypress run-ct

      - name: Start Dev Server
        working-directory: server
        run: npm run dev &

      - name: Cypress End to End
        run: npm run client:integration
